# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.10.12               # https://pyreadiness.org/3.9/
  - pip=23.2.1                  # https://pip.pypa.io/en/stable/news/
  - pip:
    # Define pip packages here -> https://pypi.org/
    # - rpaframework==26.1.2      # https://rpaframework.org/releasenotes.html
    - https://robocorp:freeasinbeer@devpi.robocorp.cloud/ci/test/+f/0ed/c00af6882c2b2/rpaframework-26.1.2-py3-none-any.whl#sha256=0edc00af6882c2b257e2e022054ff2c808f43456c2f6ae2ccc45345ea2c2a689
